export const LOAD_AUTH = "LOAD_AUTH";
export const LOAD_AUTH_SUCCESS = "LOAD_AUTH_SUCCESS";
export const LOAD_AUTH_FAIL = "LOAD_AUTH_FAIL";

export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const LOADING_UI = "LOADING_UI";
export const STOP_LOADING_UI = "STOP_LOADING_UI";

export const LOGOUT = "LOGOUT";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";

export const UPLOAD_IMAGE = "UPLOAD_IMAGE";
export const UPLOAD_IMAGE_SUCCESS = "UPLOAD_IMAGE_SUCCESS";
export const UPLOAD_IMAGE_FAIL = "UPLOAD_IMAGE_FAIL";

export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_FAIL = "UPDATE_PROFILE_FAIL";

export const REGISTER = "REGISTER";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const USER_DETAILS = "USER_DETAILS";
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS";
export const USER_DETAILS_FAIL = "USER_DETAILS_FAIL";

export const CLEAR_USER_DETAILS = "CLEAR_USER_DETAILS";

export const USER_ADD_WOOF = "USER_ADD_WOOF";

export const LOAD_WOOFS = "LOAD_WOOFS";
export const LOAD_WOOFS_SUCCESS = "LOAD_WOOFS_SUCCESS";
export const LOAD_WOOFS_FAIL = "LOAD_WOOFS_FAIL";

export const LOAD_SINGLE_WOOF = "LOAD_SINGLE_WOOF";
export const LOAD_SINGLE_WOOF_SUCCESS = "LOAD_SINGLE_WOOF_SUCCESS";
export const LOAD_SINGLE_WOOF_FAIL = "LOAD_SINGLE_WOOF_FAIL";

export const LIKE_WOOF = "LIKE_WOOF";
export const LIKE_WOOF_SUCCESS = "LIKE_WOOF_SUCCESS";
export const LIKE_WOOF_FAIL = "LIKE_WOOF_FAIL";

export const UN_LIKE_WOOF = "UN_LIKE_WOOF";
export const UN_LIKE_WOOF_SUCCESS = "UN_LIKE_WOOF_SUCCESS";
export const UN_LIKE_WOOF_FAIL = "UN_LIKE_WOOF_FAIL";

export const DELETE_WOOF = "DELETE_WOOF";
export const DELETE_WOOF_SUCCESS = "DELETE_WOOF_SUCCESS";
export const DELETE_WOOF_FAIL = "DELETE_WOOF_FAIL";

export const ADD_WOOF = "ADD_WOOF";
export const ADD_WOOF_SUCCESS = "ADD_WOOF_SUCCESS";
export const ADD_WOOF_FAIL = "ADD_WOOF_FAIL";

export const ADD_COMMENT = "ADD_COMMENT";
export const ADD_COMMENT_SUCCESS = "ADD_COMMENT_SUCCESS";
export const ADD_COMMENT_FAIL = "ADD_COMMENT_FAIL";

export const MARK_NOTIFICATIONS_READ = "MARK_NOTIFICATIONS_READ";
export const MARK_NOTIFICATIONS_READ_SUCCESS =
  "MARK_NOTIFICATIONS_READ_SUCCESS";
export const MARK_NOTIFICATIONS_READ_FAIL = "MARK_NOTIFICATIONS_READ_FAIL";

export const CLEAR_UI_ERRORS = "CLEAR_UI_ERRORS";
